### ISSUE TITLE
Retry strategy not employed for first connection attempt

### ISSUE THREAD

**Issue by 0xabadea** [zalando-nakadi/fahrschein#298] opened 2022-02-16 13:42 UTC
**Describe the bug**
The first connection attempt in `NakadiReader` happens outside the retry strategy (outside any try..catch statement), really. See line 278 in version 0.18.0 (`JsonInput jsonInput = openJsonInput()`). If it fails, throws the exception and no further attempt to connect is made.

**To Reproduce**
1. Create Subscription to event type with a single partition
2. Stream Events with some other clients
3. Attempt to listen to the same subscription with Fahrschein. That is, use NakadiClient to create a runnable and call run on it. Since the subscription has a single streaming slot, this will throw an exception.

**Expected behavior**
I expected the runnable to retry. Consider the behavior when the first `openJsonInput` succeeds, but the connection is later closed by Nakadi. Then the runnable/NakadiReader will employ the retry strategy and perform retries.

**Logs**
```
Exception in thread "Thread-3" java.io.UncheckedIOException: org.zalando.fahrschein.IOProblem: Problem [about:blank] with status [409]: [Conflict] [No free slots for streaming available for subscription 19e08e52-4df2-474c-a7d1-d63d6314cef4. Total slots: 1]
    at org.zalando.fahrschein.IORunnable.lambda$unchecked$0(IORunnable.java:15)
    at java.lang.Thread.run(Thread.java:750)
Caused by: org.zalando.fahrschein.IOProblem: Problem [about:blank] with status [409]: [Conflict] [No free slots for streaming available for subscription 19e08e52-4df2-474c-a7d1-d63d6314cef4. Total slots: 1]
    at org.zalando.fahrschein.ProblemHandlingRequest.handleProblem(ProblemHandlingRequest.java:105)
    at org.zalando.fahrschein.ProblemHandlingRequest.execute(ProblemHandlingRequest.java:53)
    at org.zalando.fahrschein.NakadiReader.openJsonInput(NakadiReader.java:155)
    at org.zalando.fahrschein.NakadiReader.runInternal(NakadiReader.java:278)
    at org.zalando.fahrschein.NakadiReader.run(NakadiReader.java:266)…(more)
```

**Environment:**
 - OpenJDK 1.8.0_292
 - Fahrschein `0.18.0`

**Additional context**

**Comment by othon2000** [comment] 2022-02-21 10:31
Thanks for reporting @0xabadea . This issue needs to be addressed.

However, I started looking at the code, and I do not believe we should apply the same style of retry strategy here. Because the response `[409]: [Conflict] [No free slots for streaming available for subscription X. Total slots: Y]` is not really an error, but an expected situation. 

Instead, it makes more sense to focus only on the `409` response and retry periodically with specific settings other than inheriting, for example, `ExponentialBackoffStrategy` which is designed to deal with intermittent issues (such as outages).

**Comment by 0xabadea** [comment] 2022-02-22 08:29
The existing retry loop already handles the "no free slots" 409 just fine. There is plenty of evidence in the logs. So if you introduce new settings that focus on it, the library will present to the user two sets of settings that deal with the same error: your new settings if the error happens _during_ the first connection attempt, and the existing backoff strategy settings if the error happens _after_ the first connection attempt. That works, but it increases the cognitive effort required to use the library.

The other aspect is, what if there is an Nakadi outage during the redeployment on a service that uses Fahrschein? The outage will manifest as 500 or network errors, which would not be handled because the focus is on 409 responses. The newly deployed service will never retry and never start consuming events.

**Comment by otrosien** [comment] 2022-03-11 18:39
Duplicate of https://github.com/zalando-nakadi/fahrschein/issues/149

**Comment by otrosien** [comment] 2022-03-11 18:40
I am for retrying 409 in the same manner on first request as later.

**Comment by otrosien** [comment] 2022-08-15 16:56
Up for discussion, but I would consider changing this behaviour a breaking-change, so preferring to change it for the 2.0 release.

**Comment by otrosien** [comment] 2022-08-26 09:16
One possibility would be an opt-in to this behaviour. I'll give it a shot.

**Comment by mesut** [comment] 2023-03-22 21:21
If we make this behavior configurable, it may increase the cognitive effort required to use the library. Users would need to configure a flag along with the retry configuration. Instead, we could simplify things for the user by treating any IOException and its subclasses as temporary failures. This way, the library can guarantee that it will apply the retry strategy in case of any such failures, without requiring the user to distinguish between the first connection attempt failures or failures during event consumption.

**Comment by otrosien** [comment] 2023-03-23 07:25
I agree that for new users this is unnecessary cognitive complexity. OTOH   changing this under the hood for existing users is a bit sneaky and can lead to subtle bugs.

**Closed** 2023-03-25 15:31 UTC
Labels: bug, enhancement, release-2.0
