### ISSUE TITLE
Check the events which are published in case of Exception

### ISSUE THREAD

**Issue by karannagi** [zalando-nakadi/fahrschein#270] opened 2022-01-12 14:27 UTC
Currently the method below
`public <T> void publish(String eventName, List<T> events) throws IOException`
does not return any response, If we publish 100 records and 1 fail out of it, is there a way to know about that 1 record?
I believe the HTTP API does return the status of the records published, how do we handle it in `NakadiClient`?

**Comment by othon2000** [comment] 2022-01-12 15:23
Hi @karannagi 

Have you tested this and found that no detail is returned, or the issue is based on code analysis?

I understand this is not a very good client API, but [NakadiClient.publish](https://github.com/zalando-nakadi/fahrschein/blob/b2f0ab4d86a2ac286d99933682033bd5c468ce2b/fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java#L73) throws an [EventPublishingException extends IOException](https://github.com/zalando-nakadi/fahrschein/blob/b2f0ab4d86a2ac286d99933682033bd5c468ce2b/fahrschein/src/main/java/org/zalando/fahrschein/EventPublishingException.java#L10) if there are failures, which contains details about the failed events (only in case of a partial failure).

See also [ProblemHandlingRequest](https://github.com/zalando-nakadi/fahrschein/blob/b2f0ab4d86a2ac286d99933682033bd5c468ce2b/fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingRequest.java#L125) .

PS: for further issues, please use links to files/lines along with the snippets. Thanks!

**Comment by karannagi** [comment] 2022-01-12 15:37
Hi @othon2000 it was based on code analysis, but sure let me try catching the exception and trying.
thanks for the response.

**Comment by othon2000** [comment] 2022-01-14 12:48
Opened a PR to declare the exception and make it more visible, will close this issue.

**Closed by othon2000** 2022-01-14 12:48 UTC
